Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -9,32 +9,37 @@ jobs:
 
     steps:
       - uses: actions/checkout@v3
-      - name: Maven build & publish Talend artifacts to Talend Cloud Test jobs
-        env:
-          message: "j_test_Pricebook_SFCC_to_EARLYBIRDS_All_Files_Consumed,j_test_Pricebook_SFCC_to_EARLYBIRDS_Diffrent_XML_schema"
-        run: |
-          IFS=',' read -ra words <<< "$message"
-          for word in "${words[@]}"; do
-            echo $(echo "$word" | tr '[:upper:]' '[:lower:]')
-          done
       - run: |
-          url="https://api.eu.cloud.talend.com/tmc/v2.6/executions"
-          data='{"executable": "646254c078cf1a473c63e5fd"}'
-          response=$(curl -X POST $url -H "Content-Type: application/json" -H "Authorization: bearer -kno-jXfSKC-3vH_yLwSShQid01c-U0gQuvqeFOxD6DQHxFxsIhp6c6p1bXw2JvG" -d "$data")
-          executionId=$(echo $response | jq -r '.executionId')
-          echo $executionId
-          status=""
-          while [ "$status" != "execution_successful" ]
-          do
-            sleep 10
-            url_status=https://api.eu.cloud.talend.com/tmc/v2.6/executions/$executionId
-            response_status=$(curl -X GET $url_status -H "Content-Type: application/json" -H "Authorization: bearer -kno-jXfSKC-3vH_yLwSShQid01c-U0gQuvqeFOxD6DQHxFxsIhp6c6p1bXw2JvG")
-            status=$(echo $response_status | jq -r '.status')
-            if [ $status == "execution_failed" ]; then
-             echo "execution_failed"
-             exit 1
-           fi
-          done
+         message="test,second"
+         IFS=',' read -ra words <<< "$message"
+         main_job="${words[0]}"
+          
+#       - name: Maven build & publish Talend artifacts to Talend Cloud Test jobs
+#         env:
+#           message: "j_test_Pricebook_SFCC_to_EARLYBIRDS_All_Files_Consumed,j_test_Pricebook_SFCC_to_EARLYBIRDS_Diffrent_XML_schema"
+#         run: |
+#           IFS=',' read -ra words <<< "$message"
+#           for word in "${words[@]}"; do
+#             echo $(echo "$word" | tr '[:upper:]' '[:lower:]')
+#           done
+#       - run: |
+#           url="https://api.eu.cloud.talend.com/tmc/v2.6/executions"
+#           data='{"executable": "646254c078cf1a473c63e5fd"}'
+#           response=$(curl -X POST $url -H "Content-Type: application/json" -H "Authorization: bearer -kno-jXfSKC-3vH_yLwSShQid01c-U0gQuvqeFOxD6DQHxFxsIhp6c6p1bXw2JvG" -d "$data")
+#           executionId=$(echo $response | jq -r '.executionId')
+#           echo $executionId
+#           status=""
+#           while [ "$status" != "execution_successful" ]
+#           do
+#             sleep 10
+#             url_status=https://api.eu.cloud.talend.com/tmc/v2.6/executions/$executionId
+#             response_status=$(curl -X GET $url_status -H "Content-Type: application/json" -H "Authorization: bearer -kno-jXfSKC-3vH_yLwSShQid01c-U0gQuvqeFOxD6DQHxFxsIhp6c6p1bXw2JvG")
+#             status=$(echo $response_status | jq -r '.status')
+#             if [ $status == "execution_failed" ]; then
+#              echo "execution_failed"
+#              exit 1
+#            fi
+#           done
 
 
 #       - name: Test
